import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import "./globals.css";
import SessionProvider from "./components/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <SessionProvider>
          <header>
            <NavBar />
          </header>
          <main>{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
