import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import "./globals.css";
import SessionProvider from "./components/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <SessionProvider>
          <header>
            <NavBar />
          </header>
          <main>{children}</main>
        </SessionProvider>
        <footer className="pl-2 text-center font-mono tracking-tight text-white">
          Built by{" "}
          <a
            href="https://github.com/North-Hess/"
            className="underline underline-offset-4"
          >
            North Hess
          </a>
        </footer>
      </body>
    </html>
  );
}
